#INCLUDE "PROTHEUS.CH"
#INCLUDE "APWEBSRV.CH"
Static  cCombo:=""
/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNCVTEX00  บAutor  ณMicrosiga           บ Data ณ  04/11/15   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
Class ApiVtex

	Data cToken
	Data cKey
	Data cResponse                                      
	Data cHttp
	Data cUrl
	Data lSemAcento
	Data lUpperCase
	Data cBody
	Data cLoja
	Data cStatus
	Data cPedido
	Data lStatusPedidosResult	
	Data nPaginas
	Data nPage
	Data cIdSKU
	Data cTabelaFrete
	Data cCEP
	Data nRange
	Data cHeaderR
	Data cId
	Data cCliOrEnd

	Method New()
	Method HttpGet()	
	Method HttpPost()	
	Method Reset()	
	
	Method GetPreco()
	
	Method GetPedido()
	Method GetPedidoStatus()
	Method GetDetalhePedido()	
	Method GetFrete()	
	
	Method PedidoStatus()	
	Method PedidoStartHandling()
	Method PedidoHandling()
	Method PedidoInvoiced()
	Method CancelarPedido()	
	Method PreparandoEntrega()	
	Method ConfirmaPagamento()	

	Method GetEstoque()
	
	Method CrmBuscaCli()	
	Method CrmCliente()
	Method CrmAprovar()
	
	Method CupomMassa()
End Class  

/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNCECOMIT  บAutor  ณMicrosiga           บ Data ณ  12/04/14   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
Method New(cSistema) Class ApiVtex

Default cSistema:=""

If "UZ" $ Upper(cSistema)
  	Self:cHttp 		:= "http://uzgamesold.vtexcommercestable.com.br/"
   	Self:cKey		:= 'x-vtex-api-appKey: vtexappkey-uzgames-IFGPTV'
  	Self:cToken		:= 'x-vtex-api-appToken: IFGPTVJTASUYQELXULRECWPWHRCQHPULHJZNMYHVSSGOHPCPDVITRVFMPJICSTLLXJQHFYKWDVMJPBPROMMMGBTMDNYDQEDYHVQXYVKFKLPWJWWNUQOGGZEWPEDSAHFZ'
   	Self:cLoja		:= "uzgamesold"
ElseIf "NCGAMES" $ Upper(cSistema)
   	Self:cHttp 		:= "http://ncgames.vtexcommercestable.com.br/"
   	Self:cKey		:= 'x-vtex-api-appKey: vtexappkey-ncgames-MSPECG'
   	Self:cToken		:= 'x-vtex-api-appToken: YYTEWEQPRFWVLCRUOSFKYGJVBMXNKEYFQMKLYIFZFZSCPOYKRDMRTTWSOXCKGDFMHQEYRFWGNGFZNGGNNNWGRGLXQSXAGUSCUFUYKASMHFENNXEHRPXTHYVBFHIZHWAS'
   	Self:cLoja		:= "ncgames"     
EndIf   

Self:cUrl			:= ""
Self:cBody			:= ""
Self:lSemAcento		:= .F.
Self:lUpperCase		:= .F.
Self:nPaginas		:= 15
Self:nPage			:= "1"
Self:cIdSKU			:= ""
Self:cTabelaFrete	:= ""
Self:cCEP			:= ""
Self:nRange			:= 0
                    
  
Return Self


/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNCECOMIT  บAutor  ณMicrosiga           บ Data ณ  02/19/15   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
Method Reset() Class ApiVtex
   Self:cHttp 			:= ""
   Self:cUrl			:= ""
   Self:cBody			:= ""
   Self:lSemAcento	:= .F.
   Self:lUpperCase	:= .F.
Return Self


/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNCECOMIT  บAutor  ณMicrosiga           บ Data ณ  12/04/14   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
Method HttpGet() Class ApiVtex
Local cUrl 			:= Self:cHttp+Self:cUrl
Local cToken		:= Self:cToken
Local nTimeOut 	:= 120 
Local cParms 		:= ""
Local cBody  		:= ""
Local cHeaderRet 	:= ""
Local aHeadStr		:={}

AAdd(aHeadStr ,  Self:cKey)
AAdd(aHeadStr ,  Self:cToken)
AAdd(aHeadStr ,'Content-Type: application/json; charset=utf-8')


Self:cResponse:=HTTPQuote( cUrl, "GET", cParms, cBody, nTimeOut, aHeadStr, @cHeaderRet )

If ValType(Self:cResponse)=="C"

	Self:cResponse:=DecodeUTF8(Self:cResponse)
	
	If Self:lUpperCase
		Self:cResponse:=Upper(Self:cResponse)
	EndIf	

	If Self:lSemAcento
		Self:cResponse:=NoAcento((Self:cResponse))
	EndIf	
	
EndIf	



Return
/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNCECOMIT  บAutor  ณMicrosiga           บ Data ณ  12/09/14   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
Method HttpPost() Class ApiVtex
Local cUrl 			:= Self:cHttp+Self:cUrl
Local cToken		:= Self:cToken
Local nTimeOut 	:= 120 
Local cParms 		:= ""
Local cBody  		:= Self:cBody
Local cHeaderRet 	:= ""
Local aHeadStr		:={}

AAdd(aHeadStr ,  Self:cKey)
AAdd(aHeadStr ,  Self:cToken)
AAdd(aHeadStr ,'Content-Type: application/json; charset=utf-8')

Self:cResponse:=HTTPQuote( cUrl, "POST", cParms, cBody, nTimeOut, aHeadStr, @cHeaderRet )

If Self:lUpperCase
	Self:cResponse:=Upper(Self:cResponse)
EndIf	

If Self:lSemAcento
	Self:cResponse:=NoAcento((Self:cResponse))
EndIf	

Return


/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNCVTEX00  บAutor  ณMicrosiga           บ Data ณ  03/03/15   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
User Function xVtex()
Local oSite
Local cBody:=""
RpcSetEnv("01","03")

ChkFile("ZC5")
ChkFile("ZC6")

//u_NCVTEX04()

/*
oSite:=ApiVtex():New("UzGames")

cBody:='['
cBody+='{"wareHouseId":"1_1","itemId":"3","quantity":66},'
cBody+='{"wareHouseId":"1_2","itemId":"3","quantity":77}'
cBody+=' ]'
              
//Tabela Estoque

oSite:cUrl:="api/logistics/pvt/inventory/warehouseitems/setbalance
oSite:cBody:=cBody
oSite:HttpPost()


//Tabela Pre็o
cBody:='['
cBody+=' { "itemId": 3,"price": 1.0,"listPrice": 1.0, "validFrom": "2015-03-18 T00:00:00.000",  "validTo": "2113-12-31T00:00:00.000"  }'
cBody+=' ]'
oSite:cUrl:="/api/pricing/pvt/price-sheet"
oSite:cBody:=cBody
oSite:HttpPost()
*/

Return
/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNCVTEX00  บAutor  ณMicrosiga           บ Data ณ  03/20/15   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
Method GetPedidoStatus() Class ApiVtex
Local cUrl			:="http://oms.vtexcommerce.com.br/api/oms/pvt/orders/?an="+::cLoja+"&f_status="+::cStatus+"&page="+::nPage+"&per_page="+AllTrim(Str(::nPaginas))+"&orderBy=creationDate,desc"
Local cToken		:= Self:cToken
Local nTimeOut 		:= 120 
Local cParms 		:= ""
Local cBody  		:= ""
Local cHeaderRet 	:= ""
Local aHeadStr		:={}

AAdd(aHeadStr ,  Self:cKey)
AAdd(aHeadStr ,  Self:cToken)
AAdd(aHeadStr ,'Content-Type: application/json; charset=utf-8')

Self:cResponse:=HTTPQuote( cUrl, "GET", cParms, cBody, nTimeOut, aHeadStr, @cHeaderRet )

If ValType(Self:cResponse)=="C"

	Self:cResponse:=DecodeUTF8(Self:cResponse)
	
	If Self:lUpperCase
		Self:cResponse:=Upper(Self:cResponse)
	EndIf	

	If Self:lSemAcento
		Self:cResponse:=NoAcento((Self:cResponse))
	EndIf	
	
EndIf	
Return

/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNCVTEX00  บAutor  ณMicrosiga           บ Data ณ  04/07/15   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
Method GetDetalhePedido() Class ApiVtex
Local cUrl			:="http://oms.vtexcommerce.com.br/api/oms/pvt/orders/"+::cPedido+"/?an="+::cLoja
Local cToken		:= Self:cToken
Local nTimeOut 	:= 120 
Local cParms 		:= ""
Local cBody  		:= ""
Local cHeaderRet 	:= ""
Local aHeadStr		:={}

AAdd(aHeadStr ,  Self:cKey)
AAdd(aHeadStr ,  Self:cToken)
AAdd(aHeadStr ,'Content-Type: application/json; charset=utf-8')

Self:cResponse:=HTTPQuote( cUrl, "GET", cParms, cBody, nTimeOut, aHeadStr, @cHeaderRet )

If ValType(Self:cResponse)=="C"

	Self:cResponse:=DecodeUTF8(Self:cResponse)
	
	If !(ValType(Self:cResponse)=="C")
		Self:cResponse:=HTTPQuote( cUrl, "GET", cParms, cBody, nTimeOut, aHeadStr, @cHeaderRet )
	EndIf
	
	If Self:lUpperCase
		Self:cResponse:=Upper(Self:cResponse)
	EndIf	

	If Self:lSemAcento
		Self:cResponse:=FwNoAccent((Self:cResponse))
	EndIf
		
	
EndIf	
Return

/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNCVTEX00  บAutor  ณMicrosiga           บ Data ณ  04/10/15   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
Method PedidoStartHandling() Class ApiVtex
Local cUrl	:="http://oms.vtexcommerce.com.br/api/oms/pvt/orders/"+Self:cPedido+"/start-handling/?an="+Self:cLoja
Local cToken		:= Self:cToken
Local nTimeOut 	:= 120 
Local cParms 		:= ""
Local cBody  		:= ""
Local cHeaderRet 	:= ""
Local aHeadStr		:={}

AAdd(aHeadStr ,  Self:cKey)
AAdd(aHeadStr ,  Self:cToken)
AAdd(aHeadStr ,'Content-Type: application/json; charset=utf-8')

Self:cResponse:=HTTPQuote( cUrl, "POST", cParms, cBody, nTimeOut, aHeadStr, @cHeaderRet )

If ValType(Self:cResponse)=="C"

	Self:cResponse:=DecodeUTF8(Self:cResponse)
	
	If Self:lUpperCase
		Self:cResponse:=Upper(Self:cResponse)
	EndIf	

	If Self:lSemAcento
		Self:cResponse:=NoAcento((Self:cResponse))
	EndIf	
	
EndIf	
Return

/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNCVTEX00  บAutor  ณMicrosiga           บ Data ณ  04/10/15   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
Method PedidoHandling() Class ApiVtex
Local cUrl	:="http://oms.vtexcommerce.com.br/api/oms/pvt/orders/?an="+::cLoja+"&f_status=handling"
Local cToken		:= Self:cToken
Local nTimeOut 	:= 120 
Local cParms 		:= ""
Local cBody  		:= ""
Local cHeaderRet 	:= ""
Local aHeadStr		:={}

AAdd(aHeadStr ,  Self:cKey)
AAdd(aHeadStr ,  Self:cToken)
AAdd(aHeadStr ,'Content-Type: application/json; charset=utf-8')

Self:cResponse:=HTTPQuote( cUrl, "GET", cParms, cBody, nTimeOut, aHeadStr, @cHeaderRet )

If ValType(Self:cResponse)=="C"

	Self:cResponse:=DecodeUTF8(Self:cResponse)
	
	If Self:lUpperCase
		Self:cResponse:=Upper(Self:cResponse)
	EndIf	

	If Self:lSemAcento
		Self:cResponse:=NoAcento((Self:cResponse))
	EndIf	
	
EndIf	
Return
/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNCVTEX00  บAutor  ณMicrosiga           บ Data ณ  04/10/15   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
Method PedidoInvoiced() Class ApiVtex
Local cUrl	:="http://oms.vtexcommerce.com.br/api/oms/pvt/orders/?an="+::cLoja+"&f_status=invoiced"
Local cToken		:= Self:cToken
Local nTimeOut 	:= 120 
Local cParms 		:= ""
Local cBody  		:= ""
Local cHeaderRet 	:= ""
Local aHeadStr		:={}

AAdd(aHeadStr ,  Self:cKey)
AAdd(aHeadStr ,  Self:cToken)
AAdd(aHeadStr ,'Content-Type: application/json; charset=utf-8')

Self:cResponse:=HTTPQuote( cUrl, "GET", cParms, cBody, nTimeOut, aHeadStr, @cHeaderRet )

If ValType(Self:cResponse)=="C"

	Self:cResponse:=DecodeUTF8(Self:cResponse)
	
	If Self:lUpperCase
		Self:cResponse:=Upper(Self:cResponse)
	EndIf	

	If Self:lSemAcento
		Self:cResponse:=NoAcento((Self:cResponse))
	EndIf	
	
EndIf	
Return	

/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNCVTEX00  บAutor  ณMicrosiga           บ Data ณ  04/10/15   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
Method CancelarPedido() Class ApiVtex
Local cUrl 			:="http://oms.vtexcommerce.com.br/api/oms/pvt/orders/"+::cPedido+"/cancel/?an="+::cLoja
Local cToken		:= Self:cToken
Local nTimeOut 	:= 120 
Local cParms 		:= ""
Local cBody  		:= ""
Local cHeaderRet 	:= ""
Local aHeadStr		:={}

AAdd(aHeadStr ,  Self:cKey)
AAdd(aHeadStr ,  Self:cToken)
AAdd(aHeadStr ,'Content-Type: application/json; charset=utf-8')


Self:cResponse:=HTTPQuote( cUrl, "POST", cParms, cBody, nTimeOut, aHeadStr, @cHeaderRet )

If ValType(Self:cResponse)=="C"

	Self:cResponse:=DecodeUTF8(Self:cResponse)
	
	If Self:lUpperCase
		Self:cResponse:=Upper(Self:cResponse)
	EndIf	

	If Self:lSemAcento
		Self:cResponse:=NoAcento((Self:cResponse))
	EndIf	
	
EndIf	
Return	



/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNCVTEX00  บAutor  ณMicrosiga           บ Data ณ  04/11/15   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
Method GetEstoque()	Class ApiVtex
Local cUrl 			:= "http://"+::cLoja+".vtexcommercestable.com.br/api/logistics/pvt/inventory/itemsbalance"
Local cToken		:= Self:cToken
Local nTimeOut 	:= 120 
Local cParms 		:= ""
Local cBody  		:= Self:cBody
Local cHeaderRet 	:= ""
Local aHeadStr		:={}

AAdd(aHeadStr ,  Self:cKey)
AAdd(aHeadStr ,  Self:cToken)
AAdd(aHeadStr ,'Content-Type: application/json; charset=utf-8')

Self:cResponse:=HTTPQuote( cUrl, "POST", cParms, cBody, nTimeOut, aHeadStr, @cHeaderRet )

If Self:lUpperCase
	Self:cResponse:=Upper(Self:cResponse)
EndIf	

If Self:lSemAcento
	Self:cResponse:=NoAcento((Self:cResponse))
EndIf	
 
Return
/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNCVTEX00  บAutor  ณMicrosiga           บ Data ณ  04/12/15   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
Method PedidoStatus() Class ApiVtex
Local cUrl 			:=""
Local cToken		:= Self:cToken
Local nTimeOut 	:= 120 
Local cParms 		:= ""
Local cBody  		:= ""
Local cHeaderRet 	:= ""
Local aHeadStr		:={}
Local cVtexStatus :=""

AAdd(aHeadStr ,  Self:cKey)
AAdd(aHeadStr ,  Self:cToken)
AAdd(aHeadStr ,'Content-Type: application/json; charset=utf-8')
                
//Status: payment-pending, ready-for-handling, start-handling, handling, invoiced


If ::cStatus$"5|4"//"Pedido realizado com sucesso"

ElseIf ::cStatus=="10"//"Pagamento Confirmado"
	Self:ConfirmaPagamentoBoleto()
ElseIf ::cStatus=="15"//"Enviado para a Expedi็ใo"
	Self:PedidoStartHandling()
ElseIf ::cStatus=="16"//"Enviado para a Expedi็ใo"
	Self:PedidoStartHandling()	
ElseIf ::cStatus=="30"//"Pedido Enviado"

ElseIf ::cStatus=="90"//"Pedido Cancelado"
	Self:CancelarPedido()
	If At(Self:cPedido,Self:cResponse)>0
		Self:cResponse:="OK"
	EndIf
	
ElseIf ::cStatus=="96"//"Pedido Cancelado Credito"

ElseIf ::cStatus=="91"//"Pedido Devolvido"

EndIf

Return


/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNCVTEX00  บAutor  ณMicrosiga           บ Data ณ  04/20/15   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/

User Function VTEX00TP(cTabela)
Local aAreaAtu:=GetArea()
Local cChaveZX5:=xFilial("ZX5")+cTabela

If Empty(cCombo)                      
	ZX5->(DbSetOrder(1))//ZX5_FILIAL+ZX5_TABELA+ZX5_CHAVE
	ZX5->(DbSeek(cChaveZX5))
	Do While ZX5->(!Eof()) .And. ZX5->(ZX5_FILIAL+ZX5_TABELA)==cChaveZX5
		cCombo+=Padr(AllTrim(ZX5->ZX5_CHAVE),2)+"="+AllTrim(ZX5->ZX5_DESCRI)+";"
		ZX5->(DbSkip())
	EndDo
	cCombo:=Left(cCombo,Len(cCombo)-1)
	RestArea(aAreaAtu)
EndIf

Return cCombo

/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNCVTEX00  บAutor  ณMicrosiga           บ Data ณ  04/27/15   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
Method PreparandoEntrega() Class ApiVtex
Local cUrl		:="http://oms.vtexcommerce.com.br/api/oms/pvt/orders/"+Self:cPedido+"/invoice/?an="+Self:cLoja
Local cToken	:= Self:cToken
Local nTimeOut 	:= 120 
Local cParms 	:= ""
Local cBody  	:= Self:cBody
Local cHeaderRet:= ""
Local aHeadStr	:={}

AAdd(aHeadStr , Self:cKey)
AAdd(aHeadStr , Self:cToken)
AAdd(aHeadStr ,	'Content-Type: application/json')

Self:cResponse:=HTTPQuote( cUrl, "POST", cParms, cBody, nTimeOut, aHeadStr, @cHeaderRet )

If ValType(Self:cResponse)=="C"

	Self:cResponse:=DecodeUTF8(Self:cResponse)
	
	If Self:lUpperCase
		Self:cResponse:=Upper(Self:cResponse)
	EndIf	

	If Self:lSemAcento
		Self:cResponse:=NoAcento((Self:cResponse))
	EndIf	
	
EndIf	
Return

/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNCVTEX00  บAutor  ณMicrosiga           บ Data ณ  04/28/15   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
Method ConfirmaPagamentoBoleto() Class ApiVtex
Local cUrl 			:= "http://"+::cLoja+".vtexcommerce.com.br/api/oms/pvt/orders/"+::cPedido+"/payments/6/payment-notification"
Local cToken		:= Self:cToken
Local nTimeOut 	:= 120 
Local cParms 		:= ""
Local cBody  		:= ""
Local cHeaderRet 	:= ""
Local aHeadStr		:={}       

AAdd(aHeadStr ,  Self:cKey)
AAdd(aHeadStr ,  Self:cToken)
AAdd(aHeadStr ,'Content-Type: application/json; charset=utf-8')

Self:cResponse:=HTTPQuote( cUrl, "POST", cParms, cBody, nTimeOut, aHeadStr, @cHeaderRet )

If Self:lUpperCase
	Self:cResponse:=Upper(Self:cResponse)
EndIf	

If Self:lSemAcento
	Self:cResponse:=NoAcento((Self:cResponse))
EndIf	
 
Return


/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNCVTEX00  บAutor  ณMicrosiga           บ Data ณ  05/02/15   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/                                                              
Method GetPedido() Class ApiVtex
Local cUrl			:="http://oms.vtexcommerce.com.br/api/oms/pvt/orders/"+::cPedido+"/?an="+::cLoja
Local cToken		:= Self:cToken
Local nTimeOut 	:= 120 
Local cParms 		:= ""
Local cBody  		:= ""
Local cHeaderRet 	:= ""
Local aHeadStr		:={}

AAdd(aHeadStr ,  Self:cKey)
AAdd(aHeadStr ,  Self:cToken)
AAdd(aHeadStr ,'Content-Type: application/json; charset=utf-8')

Self:cResponse:=HTTPQuote( cUrl, "GET", cParms, cBody, nTimeOut, aHeadStr, @cHeaderRet )

If ValType(Self:cResponse)=="C"

	Self:cResponse:=DecodeUTF8(Self:cResponse)
	
	If Self:lUpperCase
		Self:cResponse:=Upper(Self:cResponse)
	EndIf	

	If Self:lSemAcento
		Self:cResponse:=NoAcento((Self:cResponse))
	EndIf	
	
EndIf	
Return



/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNCVTEX00  บAutor  ณMicrosiga           บ Data ณ  05/05/15   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/    
Method GetPreco() Class ApiVtex                                                                                              
Local cUrl			:="http://rnb.vtexcommercebeta.com.br/api/pricing/pvt/price-sheet/"+Self:cIdSKU+"/?an="+Self:cLoja
Local cToken		:= Self:cToken
Local nTimeOut 	:= 120 
Local cParms 		:= ""
Local cBody  		:= ""
Local cHeaderRet 	:= ""
Local aHeadStr		:={}

AAdd(aHeadStr ,  Self:cKey)
AAdd(aHeadStr ,  Self:cToken)
AAdd(aHeadStr ,'Content-Type: application/json; charset=utf-8')

Self:cResponse:=HTTPQuote( cUrl, "GET", cParms, cBody, nTimeOut, aHeadStr, @cHeaderRet )

If ValType(Self:cResponse)=="C"

	Self:cResponse:=DecodeUTF8(Self:cResponse)
	
	If Self:lUpperCase
		Self:cResponse:=Upper(Self:cResponse)
	EndIf	

	If Self:lSemAcento
		Self:cResponse:=NoAcento((Self:cResponse))
	EndIf	
	
EndIf	
Return

/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNCVTEX00  บAutor  ณMicrosiga           บ Data ณ  05/12/15   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
Method GetFrete() Class ApiVtex
Local cUrl			:="http://"+Self:cLoja+".vtexcommercestable.com.br/api/logistics/pvt/configuration/freights/"+::cTabelaFrete+"/"+::cCEP+"/values"
Local cToken		:= Self:cToken
Local nTimeOut 	:= 120 
Local cParms 		:= ""
Local cBody  		:= ""
Local cHeaderRet 	:= ""
Local aHeadStr		:={}

AAdd(aHeadStr ,  Self:cKey)
AAdd(aHeadStr ,  Self:cToken)
AAdd(aHeadStr ,'Content-Type: application/json; charset=utf-8')

Self:cResponse:=HTTPQuote( cUrl, "GET", cParms, cBody, nTimeOut, aHeadStr, @cHeaderRet )

If ValType(Self:cResponse)=="C"

	Self:cResponse:=DecodeUTF8(Self:cResponse)
	
	If Self:lUpperCase
		Self:cResponse:=Upper(Self:cResponse)
	EndIf	

	If Self:lSemAcento
		Self:cResponse:=NoAcento((Self:cResponse))
	EndIf	
	
EndIf	
Return
/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNCVTEX00  บAutor  ณMicrosiga           บ Data ณ  05/12/15   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
Method CrmBuscaCli() Class ApiVtex
Local cUrl			:= "http://api.vtex.com/"+Self:cLoja+"/dataentities/CL/search?_fields=id,email,approved"
Local cToken		:= Self:cToken
Local nTimeOut 	:= 120 
Local cParms 		:= ""
Local cBody  		:= ""
Local cHeaderRet 	:= ""
Local aHeadStr		:= {} 

Local cRangeFim	:= AllTrim(Str(Self:nRange))
Local cRangeIni	:= AllTrim(Str(IIf(Self:nRange==0,0,Self:nRange-100)))

AAdd(aHeadStr , Self:cKey)
AAdd(aHeadStr , Self:cToken)
AAdd(aHeadStr , 'Content-Type: application/json; charset=utf-8')
AAdd(aHeadStr , 'Accept: application/vnd.vtex.ds.v10+json') 

If cRangeFim!="0"
	AAdd(aHeadStr , 'REST-Range: resources='+cRangeIni+'-'+cRangeFim+'')
EndIf

Self:cResponse:=HTTPQuote( cUrl, "GET", cParms, cBody, nTimeOut, aHeadStr, @cHeaderRet )

Self:cHeaderR := cHeaderRet

If ValType(Self:cResponse)=="C"

	Self:cResponse:=DecodeUTF8(Self:cResponse)
	
	If Self:lUpperCase
		Self:cResponse:=Upper(Self:cResponse)
	EndIf	

	If Self:lSemAcento
		Self:cResponse:=NoAcento((Self:cResponse))
	EndIf	
	
EndIf 
	
Return 


/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNCVTEX00  บAutor  ณMicrosiga           บ Data ณ  06/21/15   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
Method CrmCliente() Class ApiVtex 

Local cUrl			:= "http://"+Self:cLoja+".vtexcommercestable.com.br/api/profile-system/pvt/profiles/"+Self:cId+"/"+Self:cCliOrEnd+""
Local cToken		:= Self:cToken
Local nTimeOut 	:= 120 
Local cParms 		:= ""
Local cBody  		:= ""
Local cHeaderRet 	:= ""
Local aHeadStr		:= {}

AAdd(aHeadStr , Self:cKey)
AAdd(aHeadStr , Self:cToken)
AAdd(aHeadStr , 'Content-Type: application/json; charset=utf-8')

Self:cResponse:=HTTPQuote( cUrl, "GET", cParms, cBody, nTimeOut, aHeadStr, @cHeaderRet )

If ValType(Self:cResponse)=="C"

	Self:cResponse:=DecodeUTF8(Self:cResponse)
	
	If Self:lUpperCase
		Self:cResponse:=Upper(Self:cResponse)
	EndIf	

	If Self:lSemAcento
		Self:cResponse:=NoAcento((Self:cResponse))
	EndIf	
	
EndIf 
	
Return 


/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNCVTEX00  บAutor  ณMicrosiga           บ Data ณ  06/21/15   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
Method CrmAprovar() Class ApiVtex 

Local cUrl			:= "http://profilesystem.vtex.com.br/api/profile-system/pvt/profiles/"+Self:cId+"/"+Self:cCliOrEnd+"?an="+Self:cLoja+""
Local cToken		:= Self:cToken
Local nTimeOut 	:= 120 
Local cParms 		:= ""
Local cBody  		:= ""
Local cHeaderRet 	:= ""
Local aHeadStr		:= {}

AAdd(aHeadStr , Self:cKey)
AAdd(aHeadStr , Self:cToken)
AAdd(aHeadStr , 'Content-Type: application/json; charset=utf-8')
AAdd(aHeadStr , 'Accept: application/vnd.vtex.ds.v10+json') 

Self:cResponse:=HTTPQuote( cUrl, "POST", cParms, cBody, nTimeOut, aHeadStr, @cHeaderRet )

If ValType(Self:cResponse)=="C"

	Self:cResponse:=DecodeUTF8(Self:cResponse)
	
	If Self:lUpperCase
		Self:cResponse:=Upper(Self:cResponse)
	EndIf	

	If Self:lSemAcento
		Self:cResponse:=NoAcento((Self:cResponse))
	EndIf	
	
EndIf 
	
Return


/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNCVTEX00  บAutor  ณMicrosiga           บ Data ณ  06/23/15   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
//Method CrmBuscaId() Class ApiVtex
              
//Local cUrl := "http://profilesystem.vtex.com.br/api/profile-system/pvt/profiles/sk-?surrogateKey=erick.herrera@vtex.com.br&an=ncgames"
/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณNCVTEX00  บAutor  ณMicrosiga           บ Data ณ  08/17/16   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ                                                            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
Method CupomMassa() Class ApiVtex 

Local cUrl			:= "http://rnb.vtexcommercestable.com.br/api/rnb/pvt/coupon?an="+Self:cLoja+""
Local cToken		:= Self:cToken
Local nTimeOut 	:= 120 
Local cParms 		:= ""
Local cBody  		:= Self:cBody
Local cHeaderRet 	:= ""
Local aHeadStr	:= {}

AAdd(aHeadStr , Self:cKey)
AAdd(aHeadStr , Self:cToken)
AAdd(aHeadStr , 'Content-Type: application/json')

Self:cResponse:=HTTPQuote( cUrl, "POST", cParms, cBody, nTimeOut, aHeadStr, @cHeaderRet )

If ValType(cHeaderRet)=="C"

	Self:cResponse:= cHeaderRet
	
EndIf 
	
Return
